version: '3'
networks:
  movieDB_network_compose:
    driver: bridge 
services:
  db:
    image: mysql
    restart: always
    healthcheck:
        test: exit 0
    environment:
        MYSQL_DATABASE: movieDB
        # So you don't have to use root, but you can if you like
        MYSQL_USER: movieDB
        # You can use whatever password you like
        MYSQL_PASSWORD: movieDB
        # Password for root access
        MYSQL_ROOT_PASSWORD: password
    ports:
         # <Port exposed> : <MySQL Port running inside container>
        - 3306:3306
    expose:
        # Opens port 3306 on the container
        - '3306'
    # Where our data will be persisted
    volumes:
        - my-db:/var/lib/mysql
volumes:
    my-db: